### PR TITLE
fix cancellation when stdout is consumed, see #23

### LINKED ISSUE #23: capture mode "Consume" prevents cancellation of the process
I expected that I could just cancel the coroutine and the process would cancel automatically. But this did not work in my project: https://github.com/StefanLobbenmeier/yt-dlp-compose/pull/115

I then created a very simple example project to reproduce the issue, could you take a look?
https://github.com/StefanLobbenmeier/cancel-process-jetpack-compose

As I understand it this should work from version 1.3 onwards, but maybe I misunderstood something about how to actually cancel it

~~In the unit test only the job is cancelled, so that is something for me to try next: 
https://github.com/pgreze/kotlin-process/blob/5c7c931567f746e24825c6434ddbe70a79c8f8c7/src/test/kotlin/com/github/pgreze/process/ProcessKtTest.kt#L204C1-L231C6~~

The unit test did not include the capture mode of Consume, which was the culprit, the other differences (cancel job vs cancel scope) did not matter it seems

### PR DESCRIPTION
**Pull request by StefanLobbenmeier**
Fixes #23 

It seems that the call to lineflow is blocking, so it does not pick up on coroutine capture. I also think this helps with another issue I have been noticing, that when I capture both stderr and stdout I get one of them as a batch at the end.

### CODE REVIEW

File: src/test/kotlin/com/github/pgreze/process/ProcessKtTest.kt [hunk 1]
```diff
@@ -179,6 +179,30 @@ class ProcessKtTest {
...
+    fun `use consume on stdout and stderr in parallel`(
+        @TempDir dir: Path,
+    ) = runSuspendTest {
+        val stdoutAndStdErr = mutableListOf<String>()
+
+        val output = process(
+            command = arrayOf(
+                "bash",
+                "-c",
+                "(echo 1 >&2; sleep 0.1; echo 2; sleep 0.1; echo 3 >&2; sleep 0.1; echo 4; sleep 0.1;)"
```
Comment (StefanLobbenmeier) [inline src/test/kotlin/com/github/pgreze/process/ProcessKtTest.kt:192]: in my local testing, 100ms is enough to make this non flaky - with 10ms you still get those weird race conditions between stdout and stderr, not sure if there is another way to avoid them like flushing them manually or something like that

**Comment by StefanLobbenmeier** [comment]
@pgreze I am assuming the eyes means you are already reviewing? (just checking that maybe you forgot to submit review and are waiting on me, which happens to me all the time 😄) otherwise no pressure

**Review by pgreze — APPROVED** [review]
@StefanLobbenmeier thank you for your contribution and sorry for the late reply, I'm not so active on maintaining this repo because it just worked, and glad it will continue even further after your fix 👍 
It seems CI cannot run until you merge something, so let me approve and open a follow-up PR if necessary, or just create a new release with your fix 🚀

**Comment by pgreze** [comment]
@StefanLobbenmeier this fix will be available from https://github.com/pgreze/kotlin-process/releases/tag/v1.5.1 👍

**Comment by StefanLobbenmeier** [comment]
Thanks for merging ❤️, just gave 1.5.1 a try and confirmed that it works 😄
